---
title: "Github for Collab"
output:
  html_document:
    keep_md: yes
---

```{r, message=FALSE, warning=FALSE}
library(moderndive)
library(skimr)
library(GGally)
library(openintro)
library(broom) 
library(tidyverse)
library(alr4)
library(ggmosaic)
library(ggridges)
library(fivethirtyeight)
```

## San Andreas Fault

```{r}
san_andreas %>% 
  ggplot() +
  geom_bar(aes(x = worry_bigone, fill = region))
```

```{r}
san_andreas %>% 
  ggplot() +
  geom_jitter(aes(x = age, y = experience, color = prepared))
```

```{r}
san_andreas %>% 
  ggplot() +
  geom_bar(aes(x = fam_san_andreas, fill = worry_bigone))
```

## Hate Crimes

```{r}
hc<-hate_crimes[-c(9),] #observation 9 (DC) produced to much interference when combined with other data states. Also doesn't count as a state, so thought it would be best to remove it's data from data wrangling 

hc
```
```{r} 
hc %>% 
  ggplot(aes(x=median_house_inc, y=hate_crimes_per_100k_splc))+ #Southern Poverty Law Center
  geom_text(aes(label=state_abbrev),
            alpha=0.7,size=2.5) +
  geom_smooth(se = FALSE, method = "lm")
hc %>% 
  ggplot(aes(x=gini_index, y=hate_crimes_per_100k_splc))+ #Southern Poverty Law Center
  geom_text(aes(label=state_abbrev),
            alpha=0.7,size=2.5) +
  geom_smooth(se = FALSE, method = "lm")
```
```{r}
hc %>% 
  ggplot(aes(x = share_non_white, y = hate_crimes_per_100k_splc))+
  geom_text(aes(label=state_abbrev),
            alpha=0.7,size=2.5) +
  geom_smooth(se = FALSE, method = "lm")
hc %>% 
  ggplot(aes(x = share_white_poverty, y = hate_crimes_per_100k_splc))+
  geom_text(aes(label=state_abbrev),
            alpha=0.7,size=2.5) +
  geom_smooth(se = FALSE, method = "lm")
hc %>% 
  ggplot(aes(x = share_unemp_seas, y = hate_crimes_per_100k_splc))+
  geom_text(aes(label=state_abbrev),
            alpha=0.7,size=2.5) +
  geom_smooth(se = FALSE, method = "lm")
```








